#!/bin/bash
# Make deploy script executable and show setup instructions

set -euo pipefail

echo "🚀 Paljonkose - GitHub Actions Auto-Deploy Setup"
echo "================================================="
echo ""
echo "✅ Files created:"
echo "   - package.json (Node.js dependencies)"
echo "   - deploy/github/workflows/deploy.yml (GitHub Actions active)"
echo "   - DEPLOYMENT.md (complete setup guide)"
echo "   - .env.example (environment variables)"
echo "   - deploy.sh (helper script)"
echo ""
echo "📋 NEXT STEPS:"
echo ""
echo "1️⃣  Follow the setup guide:"
echo "   cat DEPLOYMENT.md"
echo ""
echo "2️⃣  Test locally:"
echo "   npm install"
echo "   npm run dev"
echo ""
echo "3️⃣  Generate SSH key for GitHub:"
echo "   ssh-keygen -t ed25519 -f deploy_key -N \"\" -C \"github-actions-deploy\""
echo ""
echo "4️⃣  Add secrets to GitHub:"
echo "   https://github.com/kirbac1/paljonkose/settings/secrets/actions"
echo "   - DEPLOY_SSH_KEY (contents of deploy_key)"
echo "   - DEPLOY_HOST (the server address)"
echo "   - DEPLOY_USER (the SSH user)"
echo "   - DEPLOY_KNOWN_HOSTS (from ssh-keyscan)"
echo ""
echo "5️⃣  Set up server directories:"
echo "   bash deploy.sh  # Choose option 3 to SSH, then run setup commands"
echo ""
echo "6️⃣  Commit and push to main:"
echo "   git add ."
echo "   git commit -m \"Configure GitHub Actions auto-deploy\""
echo "   git push origin main"
echo ""
echo "🎉 Your app will deploy automatically after each push to main!"
echo ""
